apiVersion: v1
kind: Service
metadata:
  name: even-odd-number-generator
spec:
  type: NodePort
  selector:
    app: even-odd-number-generator
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
